### PR TITLE
fix: ztdf support both base and handling assertions

### PR DESCRIPTION
**Pull request by sujankota**

### CODE REVIEW

**Review by ttschampel — COMMENTED** [review]
Can we add a unit test to cover this change?

**Comment by sujankota** [comment]
https://github.com/opentdf/java-sdk/blob/main/sdk/src/test/java/io/opentdf/platform/sdk/TDFTest.java#L210 - We have test for handling assertion

**Comment by ttschampel** [comment]
That test (or another test) doesn't actually check that both a base assertion and handling assertion result in assertions in the output TDF as far as I can tell

**Comment by sujankota** [comment]
Please check the updated test.

**Review by ttschampel — APPROVED** [review]

**Pull request merged**
